name: CI Mobile

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v4
        #uses: actions/setup-node@v4
        with:
          node-version: 20 # ajuste se necessÃ¡rio
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        
      - name: run Lint
        run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ !startsWith(fromJson(needs.setup.outputs.matrix).package[0], 'none') }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: run tests
        run: npm run test
